#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/sbin/tumgrd
CONFIGNAME="tumgrd"

start_service() {
	local enabled database interval client_bin log_level

	config_load "$CONFIGNAME"
	config_get enabled main enabled '1'
	[ "$enabled" = "1" ] || return 0

	config_get database main database '/lib/tumgrd/tumgrd.db'
	config_get interval main interval '300'
	config_get client_bin main client_bin '/usr/bin/tuctl_client'
	config_get log_level main log_level 'info'

	procd_open_instance
	procd_set_param command "$PROG" \
		-d "$database" \
		-i "$interval" \
		--client-bin "$client_bin" \
		--log-level "$log_level"

	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
